modLoader="javafml"
loaderVersion="[48,)"
license="MIT License"
[[mods]]
modId="nasty"
version="${file.jarVersion}"
displayName="Nasty Mobs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/nasty-mobs"
logoFile="logo.png"
authors="Lupicus, REchols, MacTso"
description='''Nasty Mobs.'''
[[dependencies.nasty]]
    modId="forge"
    mandatory=true
    versionRange="[48,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nasty]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"
